name: python action

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/python-flask"
          sudo docker build -t $IMAGE_NAME:latest .
          sudo docker save -o python-flask-image.tar $IMAGE_NAME:latest
          sudo chmod 644 python-flask-image.tar

      - name: upload docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: python-flask-image.tar

  push:
    runs-on: self-hosted
    needs: build
    steps:
      - name: download docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: load docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/python-flask:latest"
          sudo docker load -i python-flask-image.tar

      - name: login to docker hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: push to dockerhub
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/python-flask:latest"
          sudo docker push $IMAGE_NAME
